name: rustup
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/irondash/native_toolchain_rust.git

environment:
  sdk: '>=3.4.0-190.0.dev <4.0.0'

dependencies:
  process: ^5.0.2
  pub_semver: ^2.1.4
  native_assets_cli: ^0.4.2
  http: ^1.2.0
  logging: ^1.2.0
  path: ^1.9.0
  collection: ^1.18.0

dev_dependencies:
  file: ^7.0.0
  lints: ^3.0.0
  meta: ^1.12.0
  test: ^1.21.0
